### ISSUE TITLE
I would like to submit a PR to this new repo.  

### ISSUE THREAD

**Issue by davidschile-automox** [jfrog/terraform-provider-pipelines#1]
I've been working on a pipelines provider for a few days and I have a few resources.  I've done my best to mimic the patterns provided in the artifactory and project terraform provider projects. 
I attempted to submit a PR here, but I am unauthorized to push a new branch.  Since the repo is empty I also cannot fork.

Let me know if theres anything I can do to help with this.

Thank you.

**Comment by chb0github** [comment]
@alexhung - can we get at least a template in place so he can fork?

**Comment by alexhung** [comment]
@davidschile-automox I've pushed a bare skeleton commit to the repo. You should be able to fork and open PR when you're ready.

**Comment by alexhung** [comment]
@davidschile-automox One thing to keep in mind, TF doesn't like naming binary/provider/resource with plural form. In the 'project' provider, I had to update the repo name to singular form after the fact. I've already renamed this repo so you should be good to go.

**Comment by chb0github** [comment]
@davidschile-automox - Since no code at all is in place, please follow a few guidelines:
1. Please use `resty` as the http client - you can follow the other 3 providers as examples
2. Please steal infrastructure files from the other 3 files 

We appreciate your help. We knew we would get to this (eventually), but you're ahead of us. Projects and Xray are brand new releases and RT has been substantially upgraded
